#:schema node_modules/@deco/workers-runtime/config-schema.json
name = "htmlove"
main = "main.ts"
compatibility_date = "2025-06-17"
compatibility_flags = [ "nodejs_compat" ]

[assets]
directory = "./view-build"
binding = "ASSETS"

[deco]
workspace = "testing-workers"
enable_workflows = true
local = false

[[deco.bindings]]
name = "AI_GATEWAY"
type = "mcp"
integration_id = "i:ai-generation"

[[deco.bindings]]
name = "HOSTING_DEPLOYMENT"
type = "mcp"
integration_id = "i:hosting"

[[migrations]]
tag = "v1"
new_classes = [ "Workflow" ]

[durable_objects]
[[durable_objects.bindings]]
name = "DECO_CHAT_WORKFLOW_DO"
class_name = "Workflow"